version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run ci
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run ci
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npx lerna publish from-git
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
  tagged-deploy:
    jobs:
      - publish:
          filters:
            tags:
              only: /(.*)+@[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
